---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: "Dry-Run"
      logLevel:
        type: choice
        description: "Log-Level"
        default: debug
        options:
          - info
          - debug
          - trace
  push:
    branches:
      - master
      # branches that can be used for dry-runs
      - ci/renovate
      - ci/renovate/*
      # exclude branches created by renovate (by convention, requires respective config for renovate)
      - "!renovate/*"
      # explicitly include special branch for renovate config change PRs
      # see https://docs.renovatebot.com/config-validation/#validation-of-renovate-config-change-prs
      - "renovate/reconfigure"
  schedule:
    - cron: "0 0,2,4 * * 0"

env:
  # https://docs.renovatebot.com/troubleshooting/#log-debug-levels
  LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
  # https://docs.renovatebot.com/self-hosted-configuration/#repositories
  RENOVATE_REPOSITORIES: ${{ github.repository }}
  # https://docs.renovatebot.com/self-hosted-configuration/#username
  # If using a GitHub App as we do, the username needs to be the app name + [bot] (otherwise it fails to identify existing PRs)
  # see https://github.com/renovatebot/renovate/discussions/13708#discussioncomment-2013249
  RENOVATE_USERNAME: we-renovate[bot] # ${{ github.repository_owner }}
  # https://docs.renovatebot.com/configuration-options/#platformcommit
  RENOVATE_PLATFORM_COMMIT: "true"
  # https://docs.renovatebot.com/self-hosted-configuration/#dryrun
  # Run renovate in dry-run mode if executed in branches other than master - prevents versions in PRs/branches from being updated
  RENOVATE_DRY_RUN: "${{ inputs.dryRun || ( github.head_ref || github.ref_name ) != 'master' || false }}"
  # Allow calling Gradle wrapper (required since Renovate 43)
  # https://docs.renovatebot.com/self-hosted-configuration/#allowedunsafeexecutions
  RENOVATE_ALLOWED_UNSAFE_EXECUTIONS: '["gradleWrapper"]'
  # Renovate Automerge
  # RENOVATE_AUTOMERGE_TYPE: "branch"
  # RENOVATE_AUTOMERGE: "true"

permissions: read-all

jobs:
  renovate:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          # see https://github.com/renovatebot/renovate/blob/47c8501c412c2f53f61ca292a5039f5939c32c5d/lib/modules/platform/github/readme.md?plain=1#L28
          app-id: ${{ secrets.WE_RENOVATE_GITHUB_APP_ID }}
          private-key: "${{ secrets.WE_RENOVATE_GITHUB_PRIVATE_KEY }}"

      - name: ðŸ’¡ Self-hosted Renovate
        uses: renovatebot/github-action@44f24283a60f64273f1294932f16ba61193cccca # v46.1.0
        with:
          token: "${{ steps.app-token.outputs.token }}"
